# The URL the site will be built for
base_url = "https://www.cblanken.dev"
title = "cblanken"
compile_sass = true
build_search_index = true
theme = "terminimal-custom"
default_language = "en"
taxonomies = [
    {name = "tags", feed = true, paginate_by = 10},
]

[markdown]
highlight_code = true

[extra]
enable_post_view_navigation = true
post_view_navigation_prompt = "Read more"
logo_text = "cblanken.dev"
accent_color = "orange"

menu_items = [
    {name = "About me", url = "$BASE_URL/about"},
    {name = "Posts", url = "$BASE_URL"},
    {name = "Archive", url = "$BASE_URL/archive"},
    {name = "Tags", url = "$BASE_URL/tags"},

    {name = "github", url = "https://github.com/cblanken", newtab = true},
]

favicon = "/favicon.svg"
favicon_mimetype = "image/svg"

author = "Cameron Blankenbuehler"
