# The URL the site will be built for
base_url = "https://www.cblanken.dev"
title = "cblanken"
compile_sass = true
build_search_index = true
theme = "terminimal"
# minify_html = false
default_language = "en"

#generate_feed = true
#feed_filename = "rss.xml"

taxonomies = [
    # {name = "tags", feed = true, paginate_by = 10, render = false},
    {name = "tags", feed = true, paginate_by = 10},
]


[markdown]
# Whether to do syntax highlighting
# Theme can be customised by setting the `highlight_theme` variable to a theme supported by Zola
highlight_code = true

[extra]
enable_post_view_navigation = true
post_view_navigation_prompt = "Read more"
logo_text = "cblanken.dev"
accent_color = "orange"

menu_items = [
    {name = "About me", url = "$BASE_URL/about"},
    {name = "Posts", url = "$BASE_URL"},
    {name = "Archive", url = "$BASE_URL/archive"},
    {name = "Tags", url = "$BASE_URL/tags"},

    {name = "github", url = "https://github.com/cblanken", newtab = true},
]

# Add links to favicon, you can use https://realfavicongenerator.net/ to generate favicon for your site
[extra.favicon]
favicon_16x16 = "/icons/favicon-16x16.png"
favicon_32x32 = "/icons/favicon-32x32.png"
apple_touch_icon = "/icons/apple-touch-icon.png"
safari_pinned_tab = "/icons/safari-pinned-tab.svg"
webmanifest = "/icons/site.webmanifest"

# Author details
[extra.author]
name = "Cameron"

# Social links
[extra.social]
email = "cameron.blankenbuehler@gmail.com"
github = "cblanken"
linkedin = "cameron-blankenbuehler-508409239"
